### ISSUE TITLE
Terminology build access violation

### ISSUE THREAD

**Issue by robots** [rafspiny/enlightenment-live#42]
When building terminology-1.1.1, build is successful, but when edje_cc wants to access files outside of emerge sandbox build crashes

efl version 1.20.6

See attached buildlog:
[build.log](https://github.com/rafspiny/enlightenment-live/files/1777672/build.log)

**Comment by rafspiny** [comment]
Sorry, I must have overlooked the notification email. btw, it seems to be a problem with the ebuild. In the meantime can you try to run emerge by prefixing `env -i`? 
Other users have experienced a similar problem due to the XDG_RUNTIME_DIR env variable. It happened to me once only as well.

Please let me know if it helps while I look into it.
More details [here](https://forums.gentoo.org/viewtopic-t-1042476-start-0.html)

**Comment by rafspiny** [comment]
I assumed this can be closed.
